### ISSUE TITLE
issue when using gen-scpot.py

### ISSUE THREAD

**Issue by veritas496** [sim-kum/Surface_Charging#1]
after putting all required files into sc folder, I tried to run this script to generate each charge folder. But I meet this error info
```python
(base) [yaniguan@login1 sc]$ python gen-scpot.py 
{'nelect': 218.5}
Traceback (most recent call last):
  File "/u/scratch/y/yaniguan/amination/cu111/slab/2/lsol/sc/gen-scpot.py", line 102, in <module>
    scrun.setup()
  File "/u/scratch/y/yaniguan/amination/cu111/slab/2/lsol/sc/gen-scpot.py", line 80, in setup
    subprocess.call(['sbatch', 'ase.sh'])
  File "/u/home/y/yaniguan/miniconda3/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/u/home/y/yaniguan/miniconda3/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/u/home/y/yaniguan/miniconda3/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sbatch'
```

I guess this error info is due to this script is used in slurm cluster. I was confused how to fix this issue. I tried pbs keyword to replace sbatch since hoffman2 is a kind of  PBS cluster, but it doesn't work.

Could you please help me fix this problem?
Thanks

**Comment by sim-kum** [comment]
Hey Yani,

In the gen-scpot.py on line 80, you will see the command that directly submits all the submission scripts (job.sh). The comment right now is "batch job. sh" , For Hoffman you might have to change the comment to qsub job.sh

**Comment by veritas496** [comment]
Thanks, it works!
